package lk.ijse.restaurant.util;

public enum Routes {
    ADMIN_DASHBOARD,DASHBOARD,AD_USER,AD_STAFF,AD_ORDERS,LOGOUT,AD_TABLES,STOCK,SUPPLIER,PROFILE,SETTING,CASHIER_DASHBOARD,DASHBOARD2,
    CUSTOMER,CA_TABLE,CA_ORDERS,CA_PROFILE,CA_SETTING,PRODUCTS,PAYMENT,PLACE_ORDER,BILL

}
